/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shrey' at '11/2/15 3:27 PM' with Gradle 2.8
 *
 * @author shrey, @date 11/2/15 3:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
